
export const README_URL = "https://raw.githubusercontent.com/0aicoder0/Ultimate-Nano-Banana-Pro-Collection/main/README.md";

export const BLACKLIST_KEYWORDS = [
  "Black Friday", 
  "Special Offer", 
  "Phil Schmid", 
  "Gemini 3 Prompting", 
  "Core Principles", 
  "Tutorial", 
  "Diagram", 
  "Step-by-step", 
  "LinkedIn PDF", 
  "Signaling Pathways", 
  "Detective Board", 
  "Culinary Atlas", 
  "Alisa Fortin", 
  "Abstract 3D Render", 
  "Hand holding glowing icons",
  "How to use",
  "Table of Contents",
  "Introduction",
  "Structure of a Prompt",
  "License",
  "Credits",
  "Framework",
  "Advanced Techniques",
  "Installation",
  "Getting Started",
  "Awesome Nano Banana",
  "Decoding DRHP",
  "Luxury Home Interior",
  "16 Diverse Living Room",
  "Dystopian Mega-Corp",
  "Art Studio Oil Painting",
  "Taj Mahal Architecture",
  "Modern House Exterior",
  "Workflow",
  "Mood boards",
  "Step 2",
  "Step 3",
  "Follow, like, repost",
  "comment “Prompt”",
  "Droste effect",
  "claude.ai",
  "higgsfield_ai",
  "HUMOROUS CAPUCHIN MONKEY AT COMPUTER WITH HEADPHONES",
  "FANTASY PIXEL ART SPELL & ABILITY ICONS",
  "HAND HOLDING GLOWING DIGITAL ICONS",
  "VINTAGE TAROT CARD DECK COLLECTION",
  "HISTORIC NYC FLATIRON BUILDING",
  "BIG LEBOWSKI PIXEL ART",
  "D-DAY LANDING WWII SOLDIERS",
  "NANO BANANA AI PROMPT GENERATOR",
  "TOMB RAIDER LARA CROFT GAME ART",
  "ANIME SCI-FI PILOT IN SPACESHIP COMBAT",
  "COFFEE SHOP ART: ANIME, SKETCH & CLAYMATION",
  "AERIAL SUBURBAN LANDSCAPE",
  "EMPTY LIVING ROOM WITH BAY WINDOW"
];

export const RAW_IMAGE_PREFIX = "https://raw.githubusercontent.com/0aicoder0/Ultimate-Nano-Banana-Pro-Collection/main/";
